# Generated by Django 5.2 on 2025-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('event_invite', 'Event Invite'), ('club_announcement', 'Club Announcement'), ('message', 'Message')], default='friend_request', max_length=30),
            preserve_default=False,
        ),
    ]
