# Generated by Django 5.2 on 2025-04-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_related_id_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('club_invite', 'Club Invite'), ('message', 'Message')], max_length=30),
        ),
    ]
