# Generated by Django 5.2 on 2025-04-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubPost',
        ),
    ]
