# Generated by Django 5.2 on 2025-04-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
