# Generated by Django 5.2 on 2025-04-25 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='announcement',
        ),
    ]
