# Generated by Django 5.2 on 2025-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField()),
                ('full_name', models.TextField()),
                ('hr_name', models.TextField()),
            ],
            options={
                'db_table': 'class_info',
                'managed': False,
            },
        ),
    ]
