# Generated by Django 5.2 on 2025-04-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
