# Generated by Django 5.2 on 2025-04-22 23:53

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
