# Generated by Django 5.2 on 2025-07-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('direct_messages', '0002_message_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='class_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='courses.classinfo'),
        ),
    ]
